repos:
  - repo: https://github.com/PyCQA/isort
    rev: 6.1.0
    hooks:
      - id: isort
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: poetry run pylint
        args: ["./src", "-j=2", "--fail-under=10"]
        language: system
        types:
          - python
        require_serial: true
      